sequenceDiagram
    User ->> Device: 1. Provisioning
    Note over User,Device: Transfer CA and client<br>certificates + client private key
    Device ->> Mender Gateway: 2. Authentication request
    Mender Gateway ->> Mender Gateway: 3A. Verify Client certificate is signed by CA
    Mender Gateway -->> Device Authentication service: 3B. Authorize device<br>Using management APIs
    Mender Gateway ->> Device Authentication service: 4. Forward authentication request
    Device Authentication service ->> Mender Gateway: 5. Return the JWT token
    Mender Gateway ->> Device: 5. Return the JWT token
