sequenceDiagram
    participant User
    participant Device
    participant Device Authentication
    User ->> Device Authentication: 1. POST /api/management/v2/devauth/devices
    Note over User,Device Authentication: contains auth set (id data + public key)
    User ->> Device: 2. Transfer identity data + public key
    Device ->> Device Authentication: 3. POST /api/devices/v1/authentication/auth_requests
    Device Authentication ->> Device: 4. return JWT auth token
